# Name of the site.
name:        Voyage dans le Pacifique
# Description of the site.
description: Travel log of Barbora and Radek
# Center on UK.
timezone:    Europe/London
# Publish articles with a future date.
future:      true
# Site url.
url:         http://radekstepan.com/voyage-pacifique
# Site prefix for assets when running on GitHub Pages.
baseurl:     /voyage-pacifique
# Ignore Node.js stuff.
exclude:     [ node_modules, vendor, Gruntfile.coffee, bower.json, package.json ]

encoding:    UTF-8
markdown:    redcarpet
pygments:    true