# Name of the site.
name:        Postcard From Us
# Description of the site.
description: Travel log of Barbora and Radek
# Center on UK.
timezone:    Europe/London
# Publish articles with a future date.
future:      true
# Site url.
url:         http://postcardfrom.us
# Site prefix for assets when running on GitHub Pages; not custom domain.
baseurl:     ''
# Contact email.
email:       mail@postcardfrom.us
# Ignore Node.js stuff.
exclude:     [ node_modules, vendor, Gruntfile.coffee, bower.json, package.json, README.md, example.jpg, CNAME ]

encoding:    UTF-8
markdown:    redcarpet
pygments:    true