# Name of the site.
name:        Voyage dans le Pacifique
# Center on UK.
timezone:    Europe/London
# Publish articles with a future date.
future:      true
# Site root for assets when running on GitHub Pages.
baseurl:     http://radekstepan.com/voyage-pacifique

encoding:    UTF-8
markdown:    redcarpet
pygments:    true