# Name of the site.
name:        Voyage dans le Pacifique
# Center on UK.
timezone:    Europe/London
# Publish articles with a future date.
future:      true
# Build directory.
destination: public

encoding:    UTF-8
markdown:    redcarpet
pygments:    true