# Name of the site.
name:        Voyage dans le Pacifique
# Center on UK.
timezone:    Europe/London
# Publish articles with a future date.
future:      true
# Site prefix for assets when running on GitHub Pages.
baseurl:     /voyage-pacifique
# Ignore Node.js stuff.
exclude:     [ node_modules, vendor, Gruntfile.coffee, bower.json, package.json ]
# How many posts do we show per index page?
paginate:    3

encoding:    UTF-8
markdown:    redcarpet
pygments:    true